USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ETL_WH;
USE DATABASE CLINICAL_DWH;

CREATE OR REPLACE FILE FORMAT CLINICAL_DWH.METADATA.CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE;
