USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ETL_WH;
USE DATABASE CLINICAL_DWH;

CREATE OR REPLACE TABLE CLINICAL_DWH.RAW.DM_RAW (
  STUDYID   STRING,
  USUBJID   STRING,
  SUBJID    STRING,
  SITEID    STRING,
  AGE       NUMBER,
  SEX       STRING,
  ARM       STRING,
  COUNTRY   STRING,
  RFSTDTC   DATE
);

CREATE OR REPLACE TABLE CLINICAL_DWH.RAW.AE_RAW (
  STUDYID   STRING,
  USUBJID   STRING,
  AEDECOD   STRING,
  AEBODSYS  STRING,
  AESER     STRING,
  AESTDTC   DATE,
  AEENDTC   DATE,
  AESEV     STRING
);
