USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ETL_WH;
USE DATABASE CLINICAL_DWH;

PUT file://C:/Users/hennadiy.olshanyi/Documents/Projects/dm_raw.csv
  @CLINICAL_DWH.RAW.CLINICAL_INT_STAGE
  AUTO_COMPRESS = FALSE;

PUT file://C:/Users/hennadiy.olshanyi/Documents/Projects/ae_raw.csv
  @CLINICAL_DWH.RAW.CLINICAL_INT_STAGE
  AUTO_COMPRESS = FALSE;

  LIST @CLINICAL_DWH.RAW.CLINICAL_INT_STAGE;

-- Load DM
COPY INTO CLINICAL_DWH.RAW.DM_RAW
FROM @CLINICAL_DWH.RAW.CLINICAL_INT_STAGE/dm_raw.csv
FILE_FORMAT = (FORMAT_NAME = CLINICAL_DWH.METADATA.CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

-- Load AE
COPY INTO CLINICAL_DWH.RAW.AE_RAW
FROM @CLINICAL_DWH.RAW.CLINICAL_INT_STAGE/ae_raw.csv
FILE_FORMAT = (FORMAT_NAME = CLINICAL_DWH.METADATA.CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';


SELECT COUNT(*) FROM CLINICAL_DWH.RAW.DM_RAW;
SELECT COUNT(*) FROM CLINICAL_DWH.RAW.AE_RAW;

SELECT * FROM CLINICAL_DWH.RAW.DM_RAW LIMIT 10;
SELECT * FROM CLINICAL_DWH.RAW.AE_RAW LIMIT 10;
