USE ROLE CLINICAL_ETL_ROLE;
USE WAREHOUSE ETL_WH;
USE DATABASE CLINICAL_DWH;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_DM AS
SELECT
  STUDYID,
  USUBJID,
  SUBJID,
  SITEID,
  TRY_TO_NUMBER(AGE)         AS AGE,
  UPPER(SEX)                 AS SEX,
  ARM,
  COUNTRY,
  TO_DATE(RFSTDTC)           AS RFSTDTC,

  /* derived */
  CASE
    WHEN ARM IS NOT NULL THEN 'Y'
    ELSE 'N'
  END AS SAFFL

FROM RAW.DM_RAW;
