USE ROLE CLINICAL_ETL_ROLE;
USE WAREHOUSE ETL_WH;
USE DATABASE CLINICAL_DWH;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_AE AS
SELECT
  STUDYID,
  USUBJID,
  AEDECOD,
  AEBODSYS,
  UPPER(AESER)               AS AESER,
  UPPER(AESEV)               AS AESEV,
  TO_DATE(AESTDTC)           AS AESTDT,
  TO_DATE(AEENDTC)           AS AEENDTC,

  CASE
    WHEN UPPER(AESER) = 'Y' THEN 1
    ELSE 0
  END AS AESERFL

FROM RAW.AE_RAW;

