CREATE DATABASE IF NOT EXISTS CLINICAL_DWH;

CREATE SCHEMA IF NOT EXISTS CLINICAL_DWH.RAW;
CREATE SCHEMA IF NOT EXISTS CLINICAL_DWH.STAGING;
CREATE SCHEMA IF NOT EXISTS CLINICAL_DWH.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CLINICAL_DWH.DQ;
CREATE SCHEMA IF NOT EXISTS CLINICAL_DWH.METADATA;
