USE ROLE ACCOUNTADMIN;

-- Warehouses
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE CLINICAL_ETL_ROLE;
GRANT USAGE ON WAREHOUSE BI_WH  TO ROLE CLINICAL_ANALYST_ROLE;

-- Database
GRANT USAGE ON DATABASE CLINICAL_DWH TO ROLE CLINICAL_ETL_ROLE;
GRANT USAGE ON DATABASE CLINICAL_DWH TO ROLE CLINICAL_ANALYST_ROLE;

-- Schemas
GRANT USAGE ON SCHEMA CLINICAL_DWH.RAW       TO ROLE CLINICAL_ETL_ROLE;
GRANT USAGE ON SCHEMA CLINICAL_DWH.STAGING   TO ROLE CLINICAL_ETL_ROLE;
GRANT USAGE ON SCHEMA CLINICAL_DWH.ANALYTICS TO ROLE CLINICAL_ETL_ROLE;
GRANT USAGE ON SCHEMA CLINICAL_DWH.DQ        TO ROLE CLINICAL_ETL_ROLE;

GRANT USAGE ON SCHEMA CLINICAL_DWH.ANALYTICS TO ROLE CLINICAL_ANALYST_ROLE;
GRANT USAGE ON SCHEMA CLINICAL_DWH.DQ        TO ROLE CLINICAL_ANALYST_ROLE;

-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA CLINICAL_DWH.RAW
TO ROLE CLINICAL_ETL_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA CLINICAL_DWH.ANALYTICS
TO ROLE CLINICAL_ANALYST_ROLE;

-- Future grants
GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA CLINICAL_DWH.RAW
TO ROLE CLINICAL_ETL_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA CLINICAL_DWH.ANALYTICS
TO ROLE CLINICAL_ANALYST_ROLE;

-- Allow ETL role to use and create objects in STAGING
GRANT USAGE ON SCHEMA CLINICAL_DWH.STAGING
TO ROLE CLINICAL_ETL_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLINICAL_DWH.STAGING
TO ROLE CLINICAL_ETL_ROLE;

-- Allow ETL role to use and create objects in ANALYTICS
GRANT USAGE ON SCHEMA CLINICAL_DWH.ANALYTICS
TO ROLE CLINICAL_ETL_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLINICAL_DWH.ANALYTICS
TO ROLE CLINICAL_ETL_ROLE;
